CREATE DATABASE IF NOT EXISTS COP4331;
USE COP4331;

CREATE TABLE IF NOT EXISTS Users
(
        ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        FirstName VARCHAR(50) NOT NULL DEFAULT '',
        LastName VARCHAR(50) NOT NULL DEFAULT '',
        Login VARCHAR(50) UNIQUE NOT NULL DEFAULT '',
        Password VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Contacts
(
        ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
        FirstName VARCHAR(50) NOT NULL DEFAULT '',
        LastName VARCHAR(50) NOT NULL DEFAULT '',
        Phone VARCHAR(50) NOT NULL DEFAULT '',
        Email VARCHAR(255) NOT NULL DEFAULT '',
        UserID INT NOT NULL DEFAULT 0,
        FOREIGN KEY (UserID) REFERENCES Users(ID)
);
